### PR TITLE
Rectify bugs in the create command

### LINKED ISSUE #122: Update Create Command (FINAL)
Make sure that create command has zero bugs and fulfils all intended requirements

### PR DESCRIPTION
**Pull request by jinyang628**
Currently, there are bugs in the create command such as the equality check being sensitive to capitalisations which degrades user experience.

This needs to change because user might miscapitalise certain company names but he is referring to the same company, causing duplicates to appear in Flagship.

Rectify this capitalisation bug.

Fixes #122

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/exceptions/CommandException.java [hunk 1]
```diff
@@ -1,5 +1,7 @@
 package seedu.address.logic.commands.exceptions;
 
+import seedu.address.logic.commands.InternshipCommand;
```
Comment (javinchua) [inline src/main/java/seedu/address/logic/commands/exceptions/CommandException.java:3]: any reason for adding this since it is not being used?

**Review by javinchua — CHANGES_REQUESTED** [review]
Like the use of parameterizedtest and methodsource to reduce duplicate test code! great work just a small nitpick of unnecessary imports

File: src/main/java/seedu/address/logic/commands/exceptions/CommandException.java (hunk 1 above)
Comment (jinyang628) [reply src/main/java/seedu/address/logic/commands/exceptions/CommandException.java:3]: I need the import to write the JavaDocs for the class

**Review by javinchua — APPROVED** [review]
