### PR TITLE
Modify deadline

### LINKED ISSUE #140: [PE-D][Tester A] Incorrect error message in modify feature
When I type the command `modify 1 c/Jane Street ro/Coffee maker a/Yet to apply s/20/01/2023 de/29/11/2022 du/3 re/C++ re/Coffee`, the error message is `Start Date should only contain numbers and slashes. It must follow the form DD/MM/YYYY`. However, the start date actually follows the form DD/MM/YYYY.

Potentially problematic behaviors may include dealing with errors in the modify feature.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: ChangruHenryQian/ped#2

### LINKED ISSUE #161: [PE-D][Tester A] Incorrect error message in modify feature
As shown above, when I input `modify 1 du/1.5` to try to modify the duration to 1.5 months, I get the error message
`Internship durations should only contain positive numbers representing months and should not be blank`
even thought the input is a positive number representing 1.5 months.

A good way to improve will be to state `integer` instead of `number` in the error message, since the app only supports integer value as duration.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ChangruHenryQian/ped#5

### LINKED ISSUE #178: [PE-D][Tester B] Modify command fails on given case
Here is the list of commands I ran:

`create c/Citadel2 ro/Backend Developer a/Yet to apply de/01/02/2022 s/24/04/2022 du/2 re/C++`

`modify 1 c/Citadel ro/Backend Developer a/Yet to apply de/01/02/2022 s/24/04/2022 du/2 re/C++
`

Here is what happens if I remove the `a/Yet to apply`

`modify 1 c/Citadel ro/Backend Developer de/01/02/2022 s/24/04/2022 du/2 re/C++
`

This goes on for duplicated modifications until I can rename Citadel2 to Citadel using
`modify 1 c/Citadel`

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: MagnificentCreature/ped#12

### LINKED ISSUE #185: [PE-D][Tester D] Typo in Error Message
There is a typo in the error message given by the system, where 'earlier' and 'than' are not seperated by a space.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: joeng03/ped#2

### LINKED ISSUE #187: [PE-D][Tester D] Typo for Modify Command Success Message
The words 'Application' and 'Status' are not separated with a space.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: joeng03/ped#4

### PR DESCRIPTION
**Pull request by yongning0310**
The previous code for modify did not include a check to determine if the deadline is before the start date, which might be an issue since users would want to be notified if the edited start date or deadline is invalid.

I was unable to catch the error at the parser level due to lack of access to the model and stored data; hence, the error is now being checked at the command level. At the parser level, a dummy deadline is created with a start date that always comes after the deadline, which is the last day of the same year. However, this dummy data is removed at the command level when there is access to existing data.

I have edited the test cases to support the latest changes.

I also fixed some minor UI bugs, the issues of which are attached to this PR.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/ModifyCommand.java [hunk 1]
```diff
@@ -54,14 +57,17 @@ public class ModifyCommand extends InternshipCommand {
...
             + PREFIX_REQUIREMENT + "Python";
 
     public static final String MESSAGE_EDIT_INTERNSHIP_SUCCESS = "Edited Internship: %s";
     public static final String MESSAGE_NOT_EDITED = "At least one field to edit must be provided.";
     public static final String MESSAGE_DUPLICATE_INTERNSHIP =
-            "This internship application already exists in the tracker.";
-
+            "This internship entry with the corresponding company name and role already exists in the application.";
+    public static final String MESSAGE_DEADLINE_CONSTRAINTS =
+            "Deadline should only contain numbers and slashes. It must follow the form DD/MM/YYYY. It must be earlier"
```
Comment (shashahchk) [inline src/main/java/seedu/address/logic/commands/ModifyCommand.java:69]: Perhaps can standardise whether to use internship entry vs Internship.

File: src/main/java/seedu/address/logic/commands/ModifyCommand.java [hunk 2]
```diff
@@ -90,6 +97,26 @@ public CommandResult execute(InternshipModel model) throws CommandException {
...
+                deadline = editInternshipDescriptor.getDeadline().get().toString();
+            }
+            if (editedStartDate) {
+                startDate = editInternshipDescriptor.getStartDate().get().toString();
+            }
+            try {
+                editInternshipDescriptor.setDeadline(ParserUtil
+                        .parseDeadline(deadline, startDate));
+            } catch (ParseException e) {
+                throw new CommandException(MESSAGE_DEADLINE_CONSTRAINTS);
```
Comment (shashahchk) [inline src/main/java/seedu/address/logic/commands/ModifyCommand.java:116]: Perhaps add test case to cover this

File: src/main/java/seedu/address/logic/parser/ArgumentMultimap.java [hunk 3]
```diff
@@ -106,4 +106,14 @@ public boolean isOnlyOnePrefixPresent() {
                 .count();
         return count == 1;
     }
+
+    /**
+     * Returns true if no prefix is present.
+     */
+    public boolean noPrefixPresent() {
```
Comment (shashahchk) [inline src/main/java/seedu/address/logic/parser/ArgumentMultimap.java]: perhaps change the method name?

File: src/main/java/seedu/address/logic/parser/ModifyCommandParser.java [hunk 4]
```diff
@@ -59,10 +63,7 @@ public ModifyCommand parse(String args) throws ParseException {
         }
         if (argMultimap.getValue(PREFIX_DEADLINE).isPresent()) {
             editInternshipDescriptor.setDeadline(ParserUtil
-                    .parseDeadline(
-                            argMultimap.getValue(PREFIX_DEADLINE).get(),
-                            argMultimap.getValue(PREFIX_START_DATE).get()
-                    ));
+                    .parseDeadline(argMultimap.getValue(PREFIX_DEADLINE).get()));
```
Comment (shashahchk) [inline src/main/java/seedu/address/logic/parser/ModifyCommandParser.java:66]: Perhaps can do orElse if want to avoid error with null value when passed to parseDeadline

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 5]
```diff
@@ -104,6 +104,27 @@ public static Deadline parseDeadline(String deadline, String startDate) throws P
...
+    public static Deadline parseDeadline(String deadline) throws ParseException {
+        requireNonNull(deadline);
+        String trimmedDeadline = deadline.trim();
+        if (!Deadline.isValidDate(trimmedDeadline)) {
+            throw new ParseException(Deadline.MESSAGE_CONSTRAINTS);
+        }
+        String year = trimmedDeadline.substring(trimmedDeadline.length() - 4);
+        String placeHolderStartDate = "31/12/" + year;
+        if (!Deadline.isValidDeadline(trimmedDeadline, placeHolderStartDate)) {
+            throw new ParseException(Deadline.MESSAGE_CONSTRAINTS);
```
Comment (shashahchk) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:126]: perhaps add test case here to cover.

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 6]
```diff
@@ -104,6 +104,27 @@ public static Deadline parseDeadline(String deadline, String startDate) throws P
...
+     * @throws ParseException if the given {@code deadline} is invalid.
+     */
+    public static Deadline parseDeadline(String deadline) throws ParseException {
+        requireNonNull(deadline);
+        String trimmedDeadline = deadline.trim();
+        if (!Deadline.isValidDate(trimmedDeadline)) {
+            throw new ParseException(Deadline.MESSAGE_CONSTRAINTS);
+        }
+        String year = trimmedDeadline.substring(trimmedDeadline.length() - 4);
+        String placeHolderStartDate = "31/12/" + year;
```
Comment (shashahchk) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java]: perhaps can use LocalDate.max instead of hardcoding

File: src/test/java/seedu/address/logic/parser/ParserUtilTest.java [hunk 7]
```diff
@@ -0,0 +1,159 @@
...
+import seedu.address.model.internship.ApplicationStatus;
+import seedu.address.model.internship.CompanyName;
+import seedu.address.model.internship.Deadline;
+import seedu.address.model.internship.Duration;
+import seedu.address.model.internship.Role;
+import seedu.address.model.internship.StartDate;
+import seedu.address.model.requirement.Requirement;
+
+class ParserUtilTest {
+
```
Comment (shashahchk) [inline src/test/java/seedu/address/logic/parser/ParserUtilTest.java]: perhaps remove this extra line

**Review by pygmychameleon — CHANGES_REQUESTED** [review]
LGTM. A few nits

File: src/main/java/seedu/address/logic/parser/ModifyCommandParser.java (hunk 4 above)
Comment (yongning0310) [reply src/main/java/seedu/address/logic/parser/ModifyCommandParser.java:66]: the previous if clause already check for the case where PREFIX_DEADLINE is null

File: src/main/java/seedu/address/logic/commands/ModifyCommand.java (hunk 1 above)
Comment (yongning0310) [reply src/main/java/seedu/address/logic/commands/ModifyCommand.java:69]: changed to internship entry's

File: src/main/java/seedu/address/logic/parser/ArgumentMultimap.java (hunk 3 above)
Comment (yongning0310) [reply src/main/java/seedu/address/logic/parser/ArgumentMultimap.java]: changed to isNoPrefixPresent

File: src/main/java/seedu/address/logic/parser/ParserUtil.java (hunk 6 above)
Comment (yongning0310) [reply src/main/java/seedu/address/logic/parser/ParserUtil.java]: thanks for the suggestion

File: src/test/java/seedu/address/logic/parser/ParserUtilTest.java (hunk 7 above)
Comment (yongning0310) [reply src/test/java/seedu/address/logic/parser/ParserUtilTest.java]: removed

**Comment by shashahchk** [comment]
LGTM.

**Review by pygmychameleon — APPROVED** [review]
LGTM
