### PR TITLE
Fix filter command bug

### LINKED ISSUE #139: [PE-D][Tester E] Unclear message
The message to guide on how to use the filter function with respect to duration is not clear.

Could not tell that X-Y was referring to the months.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: nubnubyas/ped#1

### LINKED ISSUE #141: [PE-D][Tester E] Encountered bug when using filter function.
When using filter function, I typed filter `a/Yet to appl` which is a typo and resulted in an exception thrown.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: nubnubyas/ped#2

### LINKED ISSUE #148: [PE-D][Tester E] Filter command does not work as specified when searching for part of keyword.
As shown in the pictures, the behaviour when searching `filter c/Go` is not aligned with what was indicated in the UG.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: nubnubyas/ped#5

### LINKED ISSUE #153: [PE-D][Tester C] filter by company name does not work
**Steps to reproduce:**
Using the default sample list provided, run the following commands in sequence:
1. `filter c/amaz`

**Expected behavior:**
The list should be filtered to show the internship with Amazon.

**Actual behavior:**
No internships were listed.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: craigtonlian/ped#5

### LINKED ISSUE #155: [PE-D][Tester E] Inconsistent handling of inputs.
In the log, it states `deadline`,  `startdate` and `duration` follows the same format. I tried the startdate and was given that a date must be given. I tried the same for deadline and it did not work. Till now I still have not been able to figure out the correct input.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: nubnubyas/ped#7

### LINKED ISSUE #167: [PE-D][Tester B] Code allows filtering of dates from future to past
nit: `filter s/12/12/2322-23/12/2310` works(should it?), but gives no output (as expected).

Maybe this can be documented in the UG too, some users may not know which is before and after when the only documentation is X-Y, and this (highlighted) part makes it feel like it should be working.

Alternatively, you can (in the backend) sort it and make BOTH input works.

So both,
`filter du/5-2`
and 
`filter du/2-5` will display internships with duration between two to five months

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: MagnificentCreature/ped#6

### LINKED ISSUE #174: [PE-D][Tester B] Filtering with part of a name does not work
If I am to interpret this User Guide correctly, doing `filter c/JA` should match the first two characters of "Jane Street"

However, it doesn't function as intended.

Note: a Jane Street entry does exist, (the default one suggested when I enter "create")

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: MagnificentCreature/ped#10

### LINKED ISSUE #181: [PE-D][Tester A] Filter using company name does not work with a name with two words
After adding the company called Jane Street(one of the common examples in the UG) using `create c/Jane Street ro/SWE a/Yet to apply de/25/12/2022 s/20/01/2023 du/3`,  using the command `filter c/Jane Street` will not return the correct result or an error message, as shown above. Searching for one word, such as Jane, works.

You can reproduce this by the example above or dummy names like `Some Company`

Potentially problematic behaviors may include name with more words.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: ChangruHenryQian/ped#7

### LINKED ISSUE #190: [PE-D][Tester D] Invalid Command in Filter Causes Exception to be Thrown, but No Error Message is shown
When entering an invalid command such as filter c/Jane Street, a Java IllegalArgumentException is thrown in the code, but is not handled. On the user interface, no error message is shown. In fact, no message is shown at all, making the user confused about the state of the system.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: joeng03/ped#7

### PR DESCRIPTION
**Pull request by pygmychameleon**
Currently, filter command has some bugs when text input includes spaces. Another bug is deadline filter not working.

Filter command is essential to allow users to find relevant internship entries.

Let's fix the filter command to address all these bugs.

fixes #155, #190

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/FilterCommandParser.java [hunk 1]
```diff
@@ -148,19 +162,25 @@ private Predicate<Internship> parseStartDateRange(ArgumentMultimap argMultimap)
         try {
             startDateLower = parseStartDate(dateRange[0].trim());
             startDateUpper = parseStartDate(dateRange[1].trim());
+
+            if (startDateLower.compareTo(startDateUpper) > 0) {
+                throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT,
```
Comment (yongning0310) [inline src/main/java/seedu/address/logic/parser/FilterCommandParser.java:167]: can consider writing test cases that covers line 167

**Review by yongning0310 — APPROVED** [review]
LGTM
